from enum import Enum


class SCREENS(Enum):
    HOME = 0
    CONTACT_LIST = 1
    NEW_CONTACT = 2
    VIEW_CONTACT = 3
    EDIT_CONTACT = 4
    TRANSACTION_LIST = 5
    NEW_TRANSACTION = 6
    VIEW_TRANSACTION = 7
    SETTINGS = 8
    ABOUT = 9
    EDIT_TRANSACTION = 10
